import 'dotenv/config';
import { txFilter_Any, txFilter_Contract, txFilter_Standard } from './filter';

export const credConfig = {
  0: {
    title: 'Number of transactions on Basechain',
    credType: 'advanced',
    apiChoice: 'etherscan',
    apiKeyOrUrl: process.env.BASESCAN_API_KEY ?? '',
    contractAddress: 'any',
    methodId: 'any',
    network: 'basechain',
    startBlock: '0',
    endBlock: 'latest',
    filterFunction: txFilter_Any,
    mintEligibility: (result: number) => result > 0,
    transactionCountCondition: (txs: any[], address: string) =>
      txs.filter((tx) => tx.from.toLowerCase() === address.toLowerCase()).length,
  },
  1: {
    title: 'Mint a brush to save your art on the canvas',
    credType: 'basic',
    apiChoice: 'etherscan',
    apiKeyOrUrl: process.env.BASESCAN_API_KEY ?? '',
    contractAddress: '0xD68fe5b53e7E1AbeB5A4d0A6660667791f39263a',
    methodId: '0x08dc9f42',
    network: 'basechain',
    startBlock: '0',
    endBlock: 'latest',
    filterFunction: txFilter_Standard,
    transactionCondition: (txs: any[]) => txs.length > 0,
  },
  2: {
    title: 'Buy Wearables on Sofamon',
    credType: 'basic',
    apiChoice: 'etherscan',
    apiKeyOrUrl: process.env.BASESCAN_API_KEY ?? '',
    contractAddress: '0xc32dF201476BB79318C32fd696b2CcDCc5F9A909',
    methodId: '0x6cbef461',
    network: 'basechain',
    startBlock: '0',
    endBlock: 'latest',
    filterFunction: txFilter_Standard,
    transactionCondition: (txs: any[]) => txs.length > 0,
  },
  3: {
    title: 'More than 10 transactions with Frene pet',
    credType: 'basic',
    apiChoice: 'etherscan',
    apiKeyOrUrl: process.env.BASESCAN_API_KEY ?? '',
    contractAddress: '0x0e22B5f3E11944578b37ED04F5312Dfc246f443C',
    methodId: 'any',
    network: 'basechain',
    startBlock: '0',
    endBlock: 'latest',
    filterFunction: txFilter_Contract,
    transactionCondition: (txs: any[]) => txs.length > 10,
  },
  4: {
    title: 'Submit Result on Speedtracer',
    credType: 'basic',
    apiChoice: 'etherscan',
    apiKeyOrUrl: process.env.BASESCAN_API_KEY ?? '',
    contractAddress: '0xCD45E55DB12E9CA3E82370F5D0c5C6876bF6f466',
    methodId: '0x72c275a4',
    network: 'basechain',
    startBlock: '0',
    endBlock: 'latest',
    filterFunction: txFilter_Standard,
    transactionCondition: (txs: any[]) => txs.length > 0,
  },
  5: {
    title: 'Create on chain Activity on DOT',
    credType: 'basic',
    apiChoice: 'etherscan',
    apiKeyOrUrl: process.env.BASESCAN_API_KEY ?? '',
    contractAddress: '0x7b5673B598A71d27a56781271eC5fa05DE216df0',
    methodId: '0x72c275a4',
    network: 'basechain',
    startBlock: '0',
    endBlock: 'latest',
    filterFunction: txFilter_Contract,
    transactionCondition: (txs: any[]) => txs.length > 0,
  },
  6: {
    title: 'Holder of a Vrbs',
    credType: 'basic',
    apiChoice: 'contractCall',
    apiKeyOrUrl: '',
    contractAddress: '0x9ea7fd1B8823a271BEC99b205B6c0C56d7C3eAe9',
    functionName: 'balanceOf',
    abi: [
      {
        name: 'balanceOf',
        type: 'function',
        inputs: [
          {
            name: 'account',
            type: 'address',
          },
        ],
        outputs: [
          {
            name: '',
            type: 'uint256',
          },
        ],
        stateMutability: 'view',
      },
    ],
    network: 'basechain',
    contractCallCondition: (result: number) => result > 0,
  },
  7: {
    title: 'Create and Mint on paragraph.xyz',
    credType: 'basic',
    apiChoice: 'etherscan',
    apiKeyOrUrl: process.env.BASESCAN_API_KEY ?? '',
    contractAddress: '0x9Bf9D0D88C1A835F1052Ef0FBa325b35bBea127a',
    methodId: '0x3a81b8a5',
    network: 'basechain',
    startBlock: '0',
    endBlock: 'latest',
    filterFunction: txFilter_Standard,
    transactionCondition: (txs: any[]) => txs.length > 0,
  },
  8: {
    title: 'Create Collection on Zora (Base)',
    credType: 'basic',
    apiChoice: 'etherscan',
    apiKeyOrUrl: process.env.BASESCAN_API_KEY ?? '',
    contractAddress: '0x777777C338d93e2C7adf08D102d45CA7CC4Ed021',
    methodId: '0x0582823a',
    network: 'basechain',
    startBlock: '0',
    endBlock: 'latest',
    filterFunction: txFilter_Standard,
    transactionCondition: (txs: any[]) => txs.length > 0,
  },
  9: {
    title: 'Execute Swap on Uniswap (Base)',
    credType: 'basic',
    apiChoice: 'etherscan',
    apiKeyOrUrl: process.env.BASESCAN_API_KEY ?? '',
    contractAddress: '0x3fC91A3afd70395Cd496C647d5a6CC9D4B2b7FAD', // Uniswap Universal Router on Base
    methodId: '0x3593564c',
    network: 'basechain',
    startBlock: '0',
    endBlock: 'latest',
    filterFunction: txFilter_Standard,
    transactionCondition: (txs: any[]) => txs.length > 0,
  },
  10: {
    title: 'Deposit ETH to Seamless and leverage',
    credType: 'basic',
    apiChoice: 'etherscan',
    apiKeyOrUrl: process.env.BASESCAN_API_KEY ?? '',
    contractAddress: '0x5Ed6167232b937B0A5C84b49031139F405C09c8A',
    methodId: '0xbc157ac1',
    network: 'basechain',
    startBlock: '0',
    endBlock: 'latest',
    filterFunction: txFilter_Standard,
    transactionCondition: (txs: any[]) => txs.length > 0,
  },
  11: {
    title: 'Deposit USDC in PoolTogether (Base)',
    credType: 'basic',
    apiChoice: 'contractCall',
    apiKeyOrUrl: '',
    contractAddress: '0x7f5C2b379b88499aC2B997Db583f8079503f25b9',
    functionName: 'balanceOf',
    abi: [
      {
        name: 'balanceOf',
        type: 'function',
        inputs: [
          {
            name: '_account',
            type: 'address',
          },
        ],
        outputs: [
          {
            name: '',
            type: 'uint256',
          },
        ],
        stateMutability: 'view',
      },
    ],
    network: 'basechain',
    contractCallCondition: (result: number) => result > 0,
  },
  12: {
    title: 'Mint bsdETH in Reserve Protocol (Base)',
    credType: 'basic',
    apiChoice: 'etherscan',
    apiKeyOrUrl: process.env.BASESCAN_API_KEY ?? '',
    contractAddress: '0xe811b62AB97d9370cE2e25F9ceBC904522b81FE1', // bsdETH Token contract on Base
    methodId: '0xdd074ea0',
    network: 'basechain',
    startBlock: '0',
    endBlock: 'latest',
    filterFunction: txFilter_Standard,
    transactionCondition: (txs: any[]) => txs.length > 0,
  },
  13: {
    title: 'Add Liquidity on Aerodrome (Base)',
    credType: 'basic',
    apiChoice: 'etherscan',
    apiKeyOrUrl: process.env.BASESCAN_API_KEY ?? '',
    contractAddress: '0xcF77a3Ba9A5CA399B7c97c74d54e5b1Beb874E43', // Aerodrome Router contract on Base
    methodId: ['0xb7e0d4c0', '0x5a47ddc3'],
    network: 'basechain',
    startBlock: '0',
    endBlock: 'latest',
    filterFunction: txFilter_Standard,
    transactionCondition: (txs: any[]) => txs.length > 0,
  },
  14: {
    title: 'Holder of Brett Token',
    credType: 'advanced',
    apiChoice: 'contractCall',
    apiKeyOrUrl: '',
    contractAddress: '0x532f27101965dd16442E59d40670FaF5eBB142E4',
    functionName: 'balanceOf',
    abi: [
      {
        name: 'balanceOf',
        type: 'function',
        inputs: [
          {
            name: 'account',
            type: 'address',
          },
        ],
        outputs: [
          {
            name: '',
            type: 'uint256',
          },
        ],
        stateMutability: 'view',
      },
    ],
    network: 'basechain',
    mintEligibility: (result: bigint) => result > BigInt(0),
    contractCallCondition: (result: bigint) => {
      result != BigInt(0) ? result : '';
    },
  },
  15: {
    title: 'Holder of Higher Token',
    credType: 'advanced',
    apiChoice: 'contractCall',
    apiKeyOrUrl: '',
    contractAddress: '0x0578d8a44db98b23bf096a382e016e29a5ce0ffe',
    functionName: 'balanceOf',
    abi: [
      {
        name: 'balanceOf',
        type: 'function',
        inputs: [
          {
            name: 'account',
            type: 'address',
          },
        ],
        outputs: [
          {
            name: '',
            type: 'uint256',
          },
        ],
        stateMutability: 'view',
      },
    ],
    network: 'basechain',
    mintEligibility: (result: bigint) => result > BigInt(0),
    contractCallCondition: (result: bigint) => {
      result != BigInt(0) ? result : '';
    },
  },
  16: {
    title: 'Deposit USDC in Moonwell Flagship (Base)',
    credType: 'basic',
    apiChoice: 'etherscan',
    apiKeyOrUrl: process.env.BASESCAN_API_KEY ?? '',
    contractAddress: '0xc1256Ae5FF1cf2719D4937adb3bbCCab2E00A2Ca',
    methodId: '0x6e553f65',
    network: 'basechain',
    startBlock: '0',
    endBlock: 'latest',
    filterFunction: txFilter_Standard,
    transactionCondition: (txs: any[]) => txs.length > 0,
  },
  17: {
    title: 'Create Leveraged Farming Position in Extra Finance (Base)',
    credType: 'basic',
    apiChoice: 'etherscan',
    apiKeyOrUrl: process.env.BASESCAN_API_KEY ?? '',
    contractAddress: '0xf9cFB8a62f50e10AdDE5Aa888B44cF01C5957055',
    methodId: '0x4dbe83ed',
    network: 'basechain',
    startBlock: '0',
    endBlock: 'latest',
    filterFunction: txFilter_Standard,
    transactionCondition: (txs: any[]) => txs.length > 0,
  },
  18: {
    title: 'Place Bid on Yellow Collective',
    credType: 'basic',
    apiChoice: 'etherscan',
    apiKeyOrUrl: process.env.BASESCAN_API_KEY ?? '',
    contractAddress: '0x0aa23A7E112889C965010558803813710beCF263',
    methodId: ['0x659dd2b4', '0xc0d5bb8b'],
    network: 'basechain',
    startBlock: '0',
    endBlock: 'latest',
    filterFunction: txFilter_Standard,
    transactionCondition: (txs: any[]) => txs.length > 0,
  },
  19: {
    title: 'Mint Why Phi',
    credType: 'basic',
    apiChoice: 'etherscan',
    apiKeyOrUrl: process.env.BASESCAN_API_KEY ?? '',
    contractAddress: '0xc649989246FAa59bBefA7c65551cc4461E823320',
    methodId: '0x6a627842',
    network: 'basechain',
    startBlock: '0',
    endBlock: 'latest',
    filterFunction: txFilter_Standard,
    transactionCondition: (txs: any[]) => txs.length > 0,
  },
  20: {
    title: 'Contract Creator on Base',
    credType: 'basic',
    apiChoice: 'etherscan',
    apiKeyOrUrl: process.env.BASESCAN_API_KEY ?? '',
    contractAddress: 'any',
    methodId: 'any',
    network: 'basechain',
    startBlock: '0',
    endBlock: 'latest',
    filterFunction: txFilter_Any,
    transactionCondition: (txs: any[]) => {
      const contractCreationTxs = txs.filter((tx) => tx.to === '');
      return contractCreationTxs.length > 0;
    },
  },
  21: {
    title: 'Execute Trade on Avantis',
    credType: 'basic',
    apiChoice: 'etherscan',
    apiKeyOrUrl: process.env.BASESCAN_API_KEY ?? '',
    contractAddress: '0x5FF292d70bA9cD9e7CCb313782811b3D7120535f',
    methodId: '0xf5567637',
    network: 'basechain',
    startBlock: '0',
    endBlock: 'latest',
    filterFunction: txFilter_Standard,
    transactionCondition: (txs: any[]) => txs.length > 0,
  },
  22: {
    title: 'Mint cgUSD on CYGNUS FINANCE',
    credType: 'basic',
    apiChoice: 'etherscan',
    apiKeyOrUrl: process.env.BASESCAN_API_KEY ?? '',
    contractAddress: '0xCa72827a3D211CfD8F6b00Ac98824872b72CAb49',
    methodId: '0x40c10f19',
    network: 'basechain',
    startBlock: '0',
    endBlock: 'latest',
    filterFunction: txFilter_Standard,
    transactionCondition: (txs: any[]) => txs.length > 0,
  },
};
