import 'dotenv/config';
import { txFilter_Any, txFilter_Contract, txFilter_Standard } from './filter';

export const credConfig = {
  0: {
    title: 'Number of transactions on Basechain',
    description: 'Execute any transaction on Basechain',
    credType: 'ADVANCED',
    apiChoice: 'etherscan',
    apiKeyOrUrl: process.env.BASESCAN_API_KEY ?? '',
    contractAddress: 'any',
    methodId: 'any',
    network: 'basechain',
    startBlock: '0',
    endBlock: 'latest',
    filterFunction: txFilter_Any,
    mintEligibility: (result: number) => result > 0,
    transactionCountCondition: (txs: any[], address: string) =>
      txs.filter((tx) => tx.from.toLowerCase() === address.toLowerCase()).length,
    project: 'Base',
    tags: ['Transaction'],
    relatedLinks: ['https://base.org/'],
  },
  1: {
    title: 'Mint a brush to save your art on the canvas',
    description: 'Mint a Brush on Base Paint',
    credType: 'BASIC',
    apiChoice: 'etherscan',
    apiKeyOrUrl: process.env.BASESCAN_API_KEY ?? '',
    contractAddress: '0xD68fe5b53e7E1AbeB5A4d0A6660667791f39263a',
    methodId: '0x08dc9f42',
    network: 'basechain',
    startBlock: '0',
    endBlock: 'latest',
    filterFunction: txFilter_Standard,
    transactionCondition: (txs: any[]) => txs.length > 0,
    project: 'Base Paint',
    tags: ['NFT', 'Art'],
    relatedLinks: [
      'https://basepaint.xyz/brush',
      'https://basescan.org/address/0xD68fe5b53e7E1AbeB5A4d0A6660667791f39263a',
    ],
  },
  2: {
    title: 'Buy Wearables on Sofamon',
    description: 'Purchase wearables on the Sofamon platform',
    credType: 'BASIC',
    apiChoice: 'etherscan',
    apiKeyOrUrl: process.env.BASESCAN_API_KEY ?? '',
    contractAddress: '0xc32dF201476BB79318C32fd696b2cCDCc5F9A909',
    methodId: '0x6cbef461',
    network: 'basechain',
    startBlock: '0',
    endBlock: 'latest',
    filterFunction: txFilter_Standard,
    transactionCondition: (txs: any[]) => txs.length > 0,
    project: 'Sofamon',
    tags: ['NFT', 'Wearables'],
    relatedLinks: [
      'https://www.sofamon.xyz/',
      'https://basescan.org/address/0xc32df201476bb79318c32fd696b2ccdcc5f9a909',
    ],
  },
  3: {
    title: 'More than 10 transactions with Fren pet',
    description: 'Interact with Fren pet more than 10 times',
    credType: 'BASIC',
    apiChoice: 'etherscan',
    apiKeyOrUrl: process.env.BASESCAN_API_KEY ?? '',
    contractAddress: '0x0e22B5f3E11944578b37ED04F5312Dfc246f443C',
    methodId: 'any',
    network: 'basechain',
    startBlock: '0',
    endBlock: 'latest',
    filterFunction: txFilter_Contract,
    transactionCondition: (txs: any[]) => txs.length > 10,
    project: 'Frenpet',
    tags: ['Gaming', 'Pet'],
    relatedLinks: ['https://frenpet.xyz/', 'https://basescan.org/address/0x0e22B5f3E11944578b37ED04F5312Dfc246f443C'],
  },
  4: {
    title: 'Submit Result on Speedtracer',
    description: 'Submit a result on the Speedtracer platform',
    credType: 'BASIC',
    apiChoice: 'etherscan',
    apiKeyOrUrl: process.env.BASESCAN_API_KEY ?? '',
    contractAddress: '0xCD45E55DB12E9CA3E82370F5D0c5C6876bF6f466',
    methodId: '0x72c275a4',
    network: 'basechain',
    startBlock: '0',
    endBlock: 'latest',
    filterFunction: txFilter_Standard,
    transactionCondition: (txs: any[]) => txs.length > 0,
    project: 'Speedtracer',
    tags: ['Gaming'],
    relatedLinks: [
      'https://www.speedtracer.xyz/',
      'https://basescan.org/address/0xCD45E55DB12E9CA3E82370F5D0c5C6876bF6f466',
    ],
  },
  5: {
    title: 'Create on chain Activity on DOT',
    description: 'Perform an on-chain activity on DOT platform',
    credType: 'BASIC',
    apiChoice: 'etherscan',
    apiKeyOrUrl: process.env.BASESCAN_API_KEY ?? '',
    contractAddress: '0x7b5673B598A71d27a56781271eC5fa05DE216df0',
    methodId: '0x72c275a4',
    network: 'basechain',
    startBlock: '0',
    endBlock: 'latest',
    filterFunction: txFilter_Contract,
    transactionCondition: (txs: any[]) => txs.length > 0,
    project: 'DOT',
    tags: ['Social'],
    relatedLinks: ['https://dot.fan/'],
  },
  6: {
    title: 'Holder of a Vrbs',
    description: 'Own at least one Vrbs token',
    credType: 'BASIC',
    apiChoice: 'contractCall',
    apiKeyOrUrl: '',
    contractAddress: '0x9ea7fd1B8823a271BEC99b205B6c0C56d7C3eAe9',
    functionName: 'balanceOf',
    abi: [
      {
        name: 'balanceOf',
        type: 'function',
        inputs: [
          {
            name: 'account',
            type: 'address',
          },
        ],
        outputs: [
          {
            name: '',
            type: 'uint256',
          },
        ],
        stateMutability: 'view',
      },
    ],
    network: 'basechain',
    contractCallCondition: (result: number) => result > 0,
    project: 'Vrbs',
    tags: ['NFT'],
    relatedLinks: [
      'https://vrbs.build/vrbs/auction',
      'https://basescan.org/address/0x9ea7fd1b8823a271bec99b205b6c0c56d7c3eae9',
    ],
  },
  7: {
    title: 'Create and Mint on paragraph.xyz',
    description: 'Create and mint content on paragraph.xyz',
    credType: 'BASIC',
    apiChoice: 'etherscan',
    apiKeyOrUrl: process.env.BASESCAN_API_KEY ?? '',
    contractAddress: '0x9Bf9D0D88C1A835F1052Ef0FBa325b35bBea127a',
    methodId: '0x3a81b8a5',
    network: 'basechain',
    startBlock: '0',
    endBlock: 'latest',
    filterFunction: txFilter_Standard,
    transactionCondition: (txs: any[]) => txs.length > 0,
    project: 'paragraph.xyz',
    tags: ['Content', 'NFT'],
    relatedLinks: ['https://paragraph.xyz/discover/feed/recent/paragraph'],
  },
  8: {
    title: 'Create Collection on Zora (Base)',
    description: 'Create a new collection on Zora on Base network',
    credType: 'BASIC',
    apiChoice: 'etherscan',
    apiKeyOrUrl: process.env.BASESCAN_API_KEY ?? '',
    contractAddress: '0x777777C338d93e2C7adf08D102d45CA7CC4Ed021',
    methodId: '0x0582823a',
    network: 'basechain',
    startBlock: '0',
    endBlock: 'latest',
    filterFunction: txFilter_Standard,
    transactionCondition: (txs: any[]) => txs.length > 0,
    project: 'Zora',
    tags: ['NFT'],
    relatedLinks: ['https://zora.co/'],
  },
  9: {
    title: 'Execute Swap on Uniswap (Base)',
    description: 'Perform a token swap on Uniswap on Base network',
    credType: 'BASIC',
    apiChoice: 'etherscan',
    apiKeyOrUrl: process.env.BASESCAN_API_KEY ?? '',
    contractAddress: '0x3fC91A3afd70395Cd496C647d5a6CC9D4B2b7FAD',
    methodId: '0x3593564c',
    network: 'basechain',
    startBlock: '0',
    endBlock: 'latest',
    filterFunction: txFilter_Standard,
    transactionCondition: (txs: any[]) => txs.length > 0,
    project: 'Uniswap',
    tags: ['DeFi', 'Swap'],
    relatedLinks: ['https://app.uniswap.org/'],
  },
  10: {
    title: 'Deposit ETH to Seamless and leverage',
    description: 'Deposit ETH and create a leveraged position on Seamless',
    credType: 'BASIC',
    apiChoice: 'etherscan',
    apiKeyOrUrl: process.env.BASESCAN_API_KEY ?? '',
    contractAddress: '0x5Ed6167232b937B0A5C84b49031139F405C09c8A',
    methodId: '0xbc157ac1',
    network: 'basechain',
    startBlock: '0',
    endBlock: 'latest',
    filterFunction: txFilter_Standard,
    transactionCondition: (txs: any[]) => txs.length > 0,
    project: 'Seamless',
    tags: ['DeFi', 'Leverage'],
    relatedLinks: [
      'https://app.seamlessprotocol.com/#/?tab=Earn&asset=0x4200000000000000000000000000000000000006-0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913',
    ],
  },
  11: {
    title: 'Deposit USDC in PoolTogether (Base)',
    description: 'Deposit USDC into PoolTogether on Base network',
    credType: 'BASIC',
    apiChoice: 'contractCall',
    apiKeyOrUrl: '',
    contractAddress: '0x7f5C2b379b88499aC2B997Db583f8079503f25b9',
    functionName: 'balanceOf',
    abi: [
      {
        name: 'balanceOf',
        type: 'function',
        inputs: [
          {
            name: '_account',
            type: 'address',
          },
        ],
        outputs: [
          {
            name: '',
            type: 'uint256',
          },
        ],
        stateMutability: 'view',
      },
    ],
    network: 'basechain',
    contractCallCondition: (result: number) => result > 0,
    project: 'PoolTogether',
    tags: ['DeFi', 'Savings'],
    relatedLinks: ['https://app.cabana.fi/vault/8453/0x7f5C2b379b88499aC2B997Db583f8079503f25b9'],
  },
  12: {
    title: 'Mint bsdETH in Reserve Protocol (Base)',
    description: 'Mint bsdETH token in Reserve Protocol on Base network',
    credType: 'BASIC',
    apiChoice: 'etherscan',
    apiKeyOrUrl: process.env.BASESCAN_API_KEY ?? '',
    contractAddress: '0xe811b62AB97d9370cE2e25F9ceBC904522b81FE1',
    methodId: '0xdd074ea0',
    network: 'basechain',
    startBlock: '0',
    endBlock: 'latest',
    filterFunction: txFilter_Standard,
    transactionCondition: (txs: any[]) => txs.length > 0,
    project: 'Reserve Protocol',
    tags: ['DeFi', 'Stablecoin'],
    relatedLinks: [
      'https://app.reserve.org/base/token/0xcb327b99ff831bf8223cced12b1338ff3aa322ff/overview',
      'https://basescan.org/address/0xe811b62ab97d9370ce2e25f9cebc904522b81fe1',
    ],
  },
  13: {
    title: 'Add Liquidity on Aerodrome (Base)',
    description: 'Add liquidity to a pool on Aerodrome on Base network',
    credType: 'BASIC',
    apiChoice: 'etherscan',
    apiKeyOrUrl: process.env.BASESCAN_API_KEY ?? '',
    contractAddress: '0xcF77a3Ba9A5CA399B7c97c74d54e5b1Beb874E43',
    methodId: ['0xb7e0d4c0', '0x5a47ddc3'],
    network: 'basechain',
    startBlock: '0',
    endBlock: 'latest',
    filterFunction: txFilter_Standard,
    transactionCondition: (txs: any[]) => txs.length > 0,
    project: 'Aerodrome',
    tags: ['DeFi', 'Liquidity'],
    relatedLinks: [
      'https://aerodrome.finance/pools',
      'https://basescan.org/address/0xcf77a3ba9a5ca399b7c97c74d54e5b1beb874e43',
    ],
  },
  14: {
    title: 'Holder of Brett Token',
    description: 'Own at least one Brett Token',
    credType: 'ADVANCED',
    apiChoice: 'contractCall',
    apiKeyOrUrl: '',
    contractAddress: '0x532f27101965dd16442E59d40670FaF5eBB142E4',
    functionName: 'balanceOf',
    abi: [
      {
        name: 'balanceOf',
        type: 'function',
        inputs: [
          {
            name: 'account',
            type: 'address',
          },
        ],
        outputs: [
          {
            name: '',
            type: 'uint256',
          },
        ],
        stateMutability: 'view',
      },
    ],
    network: 'basechain',
    mintEligibility: (result: bigint) => result > BigInt(0),
    contractCallCondition: (result: bigint) => {
      return result != BigInt(0) ? result : '';
    },
    project: 'Brett Token',
    tags: ['Token', 'Holder'],
    relatedLinks: [
      'https://www.basedbrett.com/',
      'https://basescan.org/address/0x532f27101965dd16442e59d40670faf5ebb142e4#readContract',
    ],
  },
  15: {
    title: 'Holder of Higher Token',
    description: 'Own at least one Higher Token',
    credType: 'ADVANCED',
    apiChoice: 'contractCall',
    apiKeyOrUrl: '',
    contractAddress: '0x0578d8a44db98b23bf096a382e016e29a5ce0ffe',
    functionName: 'balanceOf',
    abi: [
      {
        name: 'balanceOf',
        type: 'function',
        inputs: [
          {
            name: 'account',
            type: 'address',
          },
        ],
        outputs: [
          {
            name: '',
            type: 'uint256',
          },
        ],
        stateMutability: 'view',
      },
    ],
    network: 'basechain',
    mintEligibility: (result: bigint) => result > BigInt(0),
    contractCallCondition: (result: bigint) => {
      return result != BigInt(0) ? result : '';
    },
    project: 'Higher Token',
    tags: ['Token', 'Holder'],
    relatedLinks: ['https://basescan.org/token/0x0578d8a44db98b23bf096a382e016e29a5ce0ffe'],
  },
  16: {
    title: 'Deposit USDC in Moonwell Flagship (Base)',
    description: 'Deposit USDC into Moonwell Flagship on Base network',
    credType: 'BASIC',
    apiChoice: 'etherscan',
    apiKeyOrUrl: process.env.BASESCAN_API_KEY ?? '',
    contractAddress: '0xc1256Ae5FF1cf2719D4937adb3bbCCab2E00A2Ca',
    methodId: '0x6e553f65',
    network: 'basechain',
    startBlock: '0',
    endBlock: 'latest',
    filterFunction: txFilter_Standard,
    transactionCondition: (txs: any[]) => txs.length > 0,
    project: 'Moonwell',
    tags: ['DeFi', 'Lending'],
    relatedLinks: [
      'https://moonwell.fi/vaults/deposit/base/mwusdc',
      'https://basescan.org/address/0x5037e7747faa78fc0ecf8dfc526dcd19f73076ce',
    ],
  },
  17: {
    title: 'Create Leveraged Farming Position in Extra Finance (Base)',
    description: 'Create a leveraged farming position on Extra Finance on Base network',
    credType: 'BASIC',
    apiChoice: 'etherscan',
    apiKeyOrUrl: process.env.BASESCAN_API_KEY ?? '',
    contractAddress: '0xf9cFB8a62f50e10AdDE5Aa888B44cF01C5957055',
    methodId: '0x4dbe83ed',
    network: 'basechain',
    startBlock: '0',
    endBlock: 'latest',
    filterFunction: txFilter_Standard,
    transactionCondition: (txs: any[]) => txs.length > 0,
    project: 'Extra Finance',
    tags: ['DeFi', 'Farming', 'Leverage'],
    relatedLinks: ['https://app.extrafi.io/farm'],
  },
  18: {
    title: 'Place Bid on Yellow Collective',
    description: 'Place a bid on Yellow Collective platform',
    credType: 'BASIC',
    apiChoice: 'etherscan',
    apiKeyOrUrl: process.env.BASESCAN_API_KEY ?? '',
    contractAddress: '0x0aa23A7E112889C965010558803813710beCF263',
    methodId: ['0x659dd2b4', '0xc0d5bb8b'],
    network: 'basechain',
    startBlock: '0',
    endBlock: 'latest',
    filterFunction: txFilter_Standard,
    transactionCondition: (txs: any[]) => txs.length > 0,
    project: 'Yellow Collective',
    tags: ['NFT', 'Auction'],
    relatedLinks: ['https://www.yellowcollective.xyz/'],
  },
  19: {
    title: 'Mint Why Phi',
    description: 'Mint a Why Phi token on Phi protocol',
    credType: 'BASIC',
    apiChoice: 'etherscan',
    apiKeyOrUrl: process.env.BASESCAN_API_KEY ?? '',
    contractAddress: '0xc649989246FAa59bBefA7c65551cc4461E823320',
    methodId: '0x6a627842',
    network: 'basechain',
    startBlock: '0',
    endBlock: 'latest',
    filterFunction: txFilter_Standard,
    transactionCondition: (txs: any[]) => txs.length > 0,
    project: 'Phi Protocol',
    tags: ['NFT', 'Minting'],
    relatedLinks: [
      'https://phiprotocol.xyz/',
      'https://basescan.org/address/0xc649989246faa59bbefa7c65551cc4461e823320',
    ],
  },
  20: {
    title: 'Contract Creator on Base',
    description: 'Deploy a smart contract on Base network',
    credType: 'BASIC',
    apiChoice: 'etherscan',
    apiKeyOrUrl: process.env.BASESCAN_API_KEY ?? '',
    contractAddress: 'any',
    methodId: 'any',
    network: 'basechain',
    startBlock: '0',
    endBlock: 'latest',
    filterFunction: txFilter_Any,
    transactionCondition: (txs: any[]) => {
      const contractCreationTxs = txs.filter((tx) => tx.to === '');
      return contractCreationTxs.length > 0;
    },
    project: 'Base',
    tags: ['Smart Contract', 'Development'],
    relatedLinks: ['https://docs.base.org/building-with-base/'],
  },
  21: {
    title: 'Execute Trade on Avantis',
    description: 'Execute a trade on Avantis platform',
    credType: 'BASIC',
    apiChoice: 'etherscan',
    apiKeyOrUrl: process.env.BASESCAN_API_KEY ?? '',
    contractAddress: '0x5FF292d70bA9cD9e7CCb313782811b3D7120535f',
    methodId: '0xf5567637',
    network: 'basechain',
    startBlock: '0',
    endBlock: 'latest',
    filterFunction: txFilter_Standard,
    transactionCondition: (txs: any[]) => txs.length > 0,
    project: 'Avantis',
    tags: ['DeFi', 'Trading'],
    relatedLinks: ['https://www.avantisfi.com/trade'],
  },
  22: {
    title: 'Mint cgUSD on CYGNUS FINANCE',
    description: 'Mint cgUSD token on CYGNUS FINANCE platform',
    credType: 'BASIC',
    apiChoice: 'etherscan',
    apiKeyOrUrl: process.env.BASESCAN_API_KEY ?? '',
    contractAddress: '0xCa72827a3D211CfD8F6b00Ac98824872b72CAb49',
    methodId: '0x40c10f19',
    network: 'basechain',
    startBlock: '0',
    endBlock: 'latest',
    filterFunction: txFilter_Standard,
    transactionCondition: (txs: any[]) => txs.length > 0,
    project: 'CYGNUS FINANCE',
    tags: ['DeFi', 'Stablecoin'],
    relatedLinks: [
      'https://app.cygnus.finance/mint',
      'https://basescan.org/tx/0x5fc2bfc66eb2c44e1e2ab2ea89479552f7f8b99c61de2afba7efdbe113b303bd',
    ],
  },
};
