import 'dotenv/config';
import { txFilter_Any, txFilter_Contract, txFilter_Standard } from './filter';

export const credConfig = {
  0: {
    title: 'Number of transactions on Basechain',
    credType: 'advanced',
    apiChoice: 'etherscan',
    apiKeyOrUrl: process.env.BASESCAN_API_KEY ?? '',
    contractAddress: 'any',
    methodId: 'any',
    network: 'basechain',
    startBlock: '0',
    endBlock: 'latest',
    filterFunction: txFilter_Any,
    transactionCountCondition: (txs: any[], address: string) =>
      txs.filter((tx) => tx.from.toLowerCase() === address.toLowerCase()).length,
  },
  1: {
    title: 'Mint a brush to save your art on the canvas',
    credType: 'basic',
    apiChoice: 'etherscan',
    apiKeyOrUrl: process.env.BASESCAN_API_KEY ?? '',
    contractAddress: '0xD68fe5b53e7E1AbeB5A4d0A6660667791f39263a',
    methodId: '0x08dc9f42',
    network: 'basechain',
    startBlock: '0',
    endBlock: 'latest',
    filterFunction: txFilter_Standard,
    transactionCondition: (txs: any[]) => txs.length > 0,
  },
  2: {
    title: 'Buy Wearables on Sofamon',
    credType: 'basic',
    apiChoice: 'etherscan',
    apiKeyOrUrl: process.env.BASESCAN_API_KEY ?? '',
    contractAddress: '0xc32dF201476BB79318C32fd696b2CcDCc5F9A909',
    methodId: '0x6cbef461',
    network: 'basechain',
    startBlock: '0',
    endBlock: 'latest',
    filterFunction: txFilter_Standard,
    transactionCondition: (txs: any[]) => txs.length > 0,
  },
  3: {
    title: 'More than 10 transactions with Frene pet',
    credType: 'basic',
    apiChoice: 'etherscan',
    apiKeyOrUrl: process.env.BASESCAN_API_KEY ?? '',
    contractAddress: '0x0e22B5f3E11944578b37ED04F5312Dfc246f443C',
    methodId: 'any',
    network: 'basechain',
    startBlock: '0',
    endBlock: 'latest',
    filterFunction: txFilter_Contract,
    transactionCondition: (txs: any[]) => txs.length > 10,
  },
  4: {
    title: 'Submit Result on Speedtracer',
    credType: 'basic',
    apiChoice: 'etherscan',
    apiKeyOrUrl: process.env.BASESCAN_API_KEY ?? '',
    contractAddress: '0xCD45E55DB12E9CA3E82370F5D0c5C6876bF6f466',
    methodId: '0x72c275a4',
    network: 'basechain',
    startBlock: '0',
    endBlock: 'latest',
    filterFunction: txFilter_Standard,
    transactionCondition: (txs: any[]) => txs.length > 0,
  },
  5: {
    title: 'Create on chain Activity on DOT',
    credType: 'basic',
    apiChoice: 'etherscan',
    apiKeyOrUrl: process.env.BASESCAN_API_KEY ?? '',
    contractAddress: '0x7b5673B598A71d27a56781271eC5fa05DE216df0',
    methodId: '0x72c275a4',
    network: 'basechain',
    startBlock: '0',
    endBlock: 'latest',
    filterFunction: txFilter_Contract,
    transactionCondition: (txs: any[]) => txs.length > 0,
  },
  6: {
    title: 'Holder of a Vrbs',
    credType: 'basic',
    apiChoice: 'contractCall',
    apiKeyOrUrl: '',
    contractAddress: '0x9ea7fd1B8823a271BEC99b205B6c0C56d7C3eAe9',
    functionName: 'balanceOf',
    abi: [
      {
        name: 'balanceOf',
        type: 'function',
        inputs: [
          {
            name: 'account',
            type: 'address',
          },
        ],
        outputs: [
          {
            name: '',
            type: 'uint256',
          },
        ],
        stateMutability: 'view',
      },
    ],
    network: 'basechain',
    contractCallCondition: (result: number) => result > 0,
  },
  7: {
    title: 'Create and Mint on paragraph.xyz',
    credType: 'basic',
    apiChoice: 'etherscan',
    apiKeyOrUrl: process.env.BASESCAN_API_KEY ?? '',
    contractAddress: '0x9Bf9D0D88C1A835F1052Ef0FBa325b35bBea127a',
    methodId: '0x3a81b8a5',
    network: 'basechain',
    startBlock: '0',
    endBlock: 'latest',
    filterFunction: txFilter_Standard,
    transactionCondition: (txs: any[]) => txs.length > 0,
  },
};
