export default [
  { inputs: [], stateMutability: 'nonpayable', type: 'constructor' },
  { inputs: [], name: 'AddressAlreadyMinted', type: 'error' },
  { inputs: [{ internalType: 'address', name: 'target', type: 'address' }], name: 'AddressEmptyCode', type: 'error' },
  { inputs: [], name: 'AddressNotSigned', type: 'error' },
  { inputs: [], name: 'ArrayLengthMismatch', type: 'error' },
  { inputs: [], name: 'ArtAlreadyCreated', type: 'error' },
  { inputs: [], name: 'ArtCreatFeeTooHigh', type: 'error' },
  { inputs: [], name: 'ArtEnded', type: 'error' },
  { inputs: [], name: 'ArtNotStarted', type: 'error' },
  { inputs: [], name: 'ClaimFailed', type: 'error' },
  { inputs: [], name: 'CreateFailed', type: 'error' },
  { inputs: [], name: 'ECDSAInvalidSignature', type: 'error' },
  {
    inputs: [{ internalType: 'uint256', name: 'length', type: 'uint256' }],
    name: 'ECDSAInvalidSignatureLength',
    type: 'error',
  },
  { inputs: [{ internalType: 'bytes32', name: 's', type: 'bytes32' }], name: 'ECDSAInvalidSignatureS', type: 'error' },
  {
    inputs: [{ internalType: 'address', name: 'implementation', type: 'address' }],
    name: 'ERC1967InvalidImplementation',
    type: 'error',
  },
  { inputs: [], name: 'ERC1967NonPayable', type: 'error' },
  { inputs: [], name: 'EndTimeInPast', type: 'error' },
  { inputs: [], name: 'EndTimeLessThanOrEqualToStartTime', type: 'error' },
  { inputs: [], name: 'EnforcedPause', type: 'error' },
  { inputs: [], name: 'ExceedMaxSupply', type: 'error' },
  { inputs: [], name: 'ExpectedPause', type: 'error' },
  { inputs: [], name: 'FailedInnerCall', type: 'error' },
  { inputs: [], name: 'InvalidAddressZero', type: 'error' },
  { inputs: [], name: 'InvalidCredCreator', type: 'error' },
  { inputs: [], name: 'InvalidEthValue', type: 'error' },
  { inputs: [], name: 'InvalidInitialization', type: 'error' },
  { inputs: [], name: 'InvalidMerkleProof', type: 'error' },
  { inputs: [], name: 'InvalidMintFee', type: 'error' },
  { inputs: [], name: 'InvalidQuantity', type: 'error' },
  { inputs: [], name: 'InvalidTimeRange', type: 'error' },
  { inputs: [], name: 'InvalidVerificationType', type: 'error' },
  { inputs: [], name: 'NotArtCreator', type: 'error' },
  { inputs: [], name: 'NotInitializing', type: 'error' },
  { inputs: [], name: 'OverMaxAllowedToMint', type: 'error' },
  { inputs: [{ internalType: 'address', name: 'owner', type: 'address' }], name: 'OwnableInvalidOwner', type: 'error' },
  {
    inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
    name: 'OwnableUnauthorizedAccount',
    type: 'error',
  },
  { inputs: [], name: 'ProtocolFeeTooHigh', type: 'error' },
  { inputs: [], name: 'Reentrancy', type: 'error' },
  { inputs: [], name: 'SignatureExpired', type: 'error' },
  { inputs: [], name: 'TxOriginMismatch', type: 'error' },
  { inputs: [], name: 'UUPSUnauthorizedCallContext', type: 'error' },
  {
    inputs: [{ internalType: 'bytes32', name: 'slot', type: 'bytes32' }],
    name: 'UUPSUnsupportedProxiableUUID',
    type: 'error',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'uint256', name: 'artId', type: 'uint256' },
      { indexed: false, internalType: 'string', name: 'verificationType', type: 'string' },
      { indexed: true, internalType: 'address', name: 'recipient', type: 'address' },
      { indexed: false, internalType: 'address', name: 'ref', type: 'address' },
      { indexed: false, internalType: 'address', name: 'verifier', type: 'address' },
      { indexed: false, internalType: 'address', name: 'artAddress', type: 'address' },
    ],
    name: 'ArtClaimedData',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'address', name: 'artist', type: 'address' },
      { indexed: false, internalType: 'address', name: 'contractAddress', type: 'address' },
      { indexed: true, internalType: 'uint256', name: 'credId', type: 'uint256' },
    ],
    name: 'ArtContractCreated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: 'uint256', name: 'percent', type: 'uint256' }],
    name: 'ArtCreatFeeSet',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'artId', type: 'uint256' },
      { indexed: false, internalType: 'string', name: 'url', type: 'string' },
      { indexed: false, internalType: 'address', name: 'artist', type: 'address' },
      { indexed: false, internalType: 'address', name: 'receiver', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'maxSupply', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'mintFee', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'startTime', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'endTime', type: 'uint256' },
      { indexed: false, internalType: 'bool', name: 'soulBounded', type: 'bool' },
    ],
    name: 'ArtUpdated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: 'address', name: 'erc1155ArtAddress', type: 'address' }],
    name: 'ERC1155ArtAddressSet',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: 'uint64', name: 'version', type: 'uint64' }],
    name: 'Initialized',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'artist', type: 'address' },
      { indexed: true, internalType: 'uint256', name: 'credId', type: 'uint256' },
      { indexed: true, internalType: 'uint256', name: 'credChainId', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'artId', type: 'uint256' },
      { indexed: false, internalType: 'string', name: 'url', type: 'string' },
      { indexed: false, internalType: 'address', name: 'artAddress', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'tokenId', type: 'uint256' },
    ],
    name: 'NewArtCreated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'previousOwner', type: 'address' },
      { indexed: true, internalType: 'address', name: 'newOwner', type: 'address' },
    ],
    name: 'OwnershipTransferStarted',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'previousOwner', type: 'address' },
      { indexed: true, internalType: 'address', name: 'newOwner', type: 'address' },
    ],
    name: 'OwnershipTransferred',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: 'address', name: 'account', type: 'address' }],
    name: 'Paused',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: 'address', name: 'phiRewardsAddress', type: 'address' }],
    name: 'PhiRewardsAddressSet',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: 'address', name: 'phiSignerAddress', type: 'address' }],
    name: 'PhiSignerAddressSet',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: 'address', name: 'protocolFeeDestination', type: 'address' }],
    name: 'ProtocolFeeDestinationSet',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: 'uint256', name: 'fee', type: 'uint256' }],
    name: 'ProtocolFeeSet',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: 'address', name: 'account', type: 'address' }],
    name: 'Unpaused',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: 'address', name: 'implementation', type: 'address' }],
    name: 'Upgraded',
    type: 'event',
  },
  {
    inputs: [],
    name: 'UPGRADE_INTERFACE_VERSION',
    outputs: [{ internalType: 'string', name: '', type: 'string' }],
    stateMutability: 'view',
    type: 'function',
  },
  { inputs: [], name: 'acceptOwnership', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  {
    inputs: [],
    name: 'artCreateFee',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'artId_', type: 'uint256' }],
    name: 'artData',
    outputs: [
      {
        components: [
          { internalType: 'uint256', name: 'credId', type: 'uint256' },
          { internalType: 'address', name: 'credCreator', type: 'address' },
          { internalType: 'uint256', name: 'credChainId', type: 'uint256' },
          { internalType: 'string', name: 'verificationType', type: 'string' },
          { internalType: 'string', name: 'uri', type: 'string' },
          { internalType: 'address', name: 'artAddress', type: 'address' },
          { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
          { internalType: 'address', name: 'artist', type: 'address' },
          { internalType: 'address', name: 'receiver', type: 'address' },
          {
            components: [
              { internalType: 'uint32', name: 'royaltyBPS', type: 'uint32' },
              { internalType: 'address', name: 'royaltyRecipient', type: 'address' },
            ],
            internalType: 'struct ICreatorRoyaltiesControl.RoyaltyConfiguration',
            name: 'royalties',
            type: 'tuple',
          },
          { internalType: 'uint256', name: 'maxSupply', type: 'uint256' },
          { internalType: 'uint256', name: 'mintFee', type: 'uint256' },
          { internalType: 'uint256', name: 'startTime', type: 'uint256' },
          { internalType: 'uint256', name: 'endTime', type: 'uint256' },
          { internalType: 'uint256', name: 'numberMinted', type: 'uint256' },
          { internalType: 'bool', name: 'soulBounded', type: 'bool' },
        ],
        internalType: 'struct IPhiFactory.ArtData',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'artIdCounter',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes[]', name: 'encodeDatas_', type: 'bytes[]' },
      { internalType: 'uint256[]', name: 'ethValue_', type: 'uint256[]' },
    ],
    name: 'batchClaim',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes32[]', name: 'proof', type: 'bytes32[]' },
      { internalType: 'bytes32', name: 'leaf', type: 'bytes32' },
      { internalType: 'bytes32', name: 'root', type: 'bytes32' },
    ],
    name: 'checkProof',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'pure',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes', name: 'encodeData_', type: 'bytes' }],
    name: 'claim',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'nftAddress', type: 'address' }],
    name: 'contractURI',
    outputs: [{ internalType: 'string', name: '', type: 'string' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes', name: 'signedData_', type: 'bytes' },
      { internalType: 'bytes', name: 'signature_', type: 'bytes' },
      {
        components: [
          { internalType: 'address', name: 'artist', type: 'address' },
          { internalType: 'address', name: 'receiver', type: 'address' },
          { internalType: 'uint256', name: 'endTime', type: 'uint256' },
          { internalType: 'uint256', name: 'startTime', type: 'uint256' },
          { internalType: 'uint256', name: 'maxSupply', type: 'uint256' },
          { internalType: 'uint256', name: 'mintFee', type: 'uint256' },
          { internalType: 'bool', name: 'soulBounded', type: 'bool' },
        ],
        internalType: 'struct IPhiFactory.CreateConfig',
        name: 'createConfig_',
        type: 'tuple',
      },
    ],
    name: 'createArt',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'credChainId', type: 'uint256' },
      { internalType: 'uint256', name: 'credId', type: 'uint256' },
    ],
    name: 'credMerkleRoot',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'erc1155ArtAddress',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'artId_', type: 'uint256' }],
    name: 'getArtAddress',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'artId_', type: 'uint256' },
      { internalType: 'uint256', name: 'quantity_', type: 'uint256' },
    ],
    name: 'getArtMintFee',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'artId_', type: 'uint256' }],
    name: 'getNumberMinted',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'artId_', type: 'uint256' }],
    name: 'getTokenURI',
    outputs: [{ internalType: 'string', name: '', type: 'string' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256[]', name: 'artId_', type: 'uint256[]' },
      { internalType: 'uint256[]', name: 'quantitys_', type: 'uint256[]' },
    ],
    name: 'getTotalMintFee',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'phiSignerAddress_', type: 'address' },
      { internalType: 'address', name: 'protocolFeeDestination_', type: 'address' },
      { internalType: 'address', name: 'erc1155ArtAddress_', type: 'address' },
      { internalType: 'address', name: 'phiRewardsAddress_', type: 'address' },
      { internalType: 'address', name: 'ownerAddress_', type: 'address' },
      { internalType: 'uint256', name: 'protocolFee_', type: 'uint256' },
      { internalType: 'uint256', name: 'artCreateFee_', type: 'uint256' },
    ],
    name: 'initialize',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'artId_', type: 'uint256' },
      { internalType: 'address', name: 'address_', type: 'address' },
    ],
    name: 'isArtMinted',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'credChainId_', type: 'uint256' },
      { internalType: 'uint256', name: 'credId_', type: 'uint256' },
      { internalType: 'address', name: 'minter_', type: 'address' },
    ],
    name: 'isCredMinted',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes32[]', name: 'proof_', type: 'bytes32[]' },
      { internalType: 'bytes', name: 'encodeData_', type: 'bytes' },
      {
        components: [
          { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
          { internalType: 'uint256', name: 'quantity', type: 'uint256' },
          { internalType: 'string', name: 'imageURI', type: 'string' },
        ],
        internalType: 'struct IPhiFactory.MintArgs',
        name: 'mintArgs_',
        type: 'tuple',
      },
      { internalType: 'bytes32', name: 'leafPart_', type: 'bytes32' },
    ],
    name: 'merkleClaim',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'mintProtocolFee',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'owner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  { inputs: [], name: 'pause', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  {
    inputs: [{ internalType: 'address', name: 'artAddress_', type: 'address' }],
    name: 'pauseArtContract',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'artId_', type: 'uint256' }],
    name: 'pauseArtContract',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'paused',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'pendingOwner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'phiRewardsAddress',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'phiSignerAddress',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'protocolFeeDestination',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'proxiableUUID',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  { inputs: [], name: 'renounceOwnership', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  {
    inputs: [{ internalType: 'uint256', name: 'artCreateFee_', type: 'uint256' }],
    name: 'setArtCreatFee',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'erc1155ArtAddress_', type: 'address' }],
    name: 'setErc1155ArtAddress',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'phiRewardsAddress_', type: 'address' }],
    name: 'setPhiRewardsAddress',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'phiSignerAddress_', type: 'address' }],
    name: 'setPhiSignerAddress',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'protocolFee_', type: 'uint256' }],
    name: 'setProtocolFee',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'protocolFeeDestination_', type: 'address' }],
    name: 'setProtocolFeeDestination',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes', name: 'signature_', type: 'bytes' },
      { internalType: 'bytes', name: 'encodeData_', type: 'bytes' },
      {
        components: [
          { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
          { internalType: 'uint256', name: 'quantity', type: 'uint256' },
          { internalType: 'string', name: 'imageURI', type: 'string' },
        ],
        internalType: 'struct IPhiFactory.MintArgs',
        name: 'mintArgs_',
        type: 'tuple',
      },
    ],
    name: 'signatureClaim',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'newOwner', type: 'address' }],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  { inputs: [], name: 'unPause', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  {
    inputs: [{ internalType: 'uint256', name: 'artId_', type: 'uint256' }],
    name: 'unPauseArtContract',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'artAddress_', type: 'address' }],
    name: 'unPauseArtContract',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'artId_', type: 'uint256' },
      { internalType: 'string', name: 'url_', type: 'string' },
      { internalType: 'address', name: 'artist_', type: 'address' },
      { internalType: 'address', name: 'receiver_', type: 'address' },
      { internalType: 'uint256', name: 'maxSupply_', type: 'uint256' },
      { internalType: 'uint256', name: 'mintFee_', type: 'uint256' },
      { internalType: 'uint256', name: 'startTime_', type: 'uint256' },
      { internalType: 'uint256', name: 'endTime_', type: 'uint256' },
      { internalType: 'bool', name: 'soulBounded_', type: 'bool' },
      {
        components: [
          { internalType: 'uint32', name: 'royaltyBPS', type: 'uint32' },
          { internalType: 'address', name: 'royaltyRecipient', type: 'address' },
        ],
        internalType: 'struct ICreatorRoyaltiesControl.RoyaltyConfiguration',
        name: 'configuration',
        type: 'tuple',
      },
    ],
    name: 'updateArtSettings',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'newImplementation', type: 'address' },
      { internalType: 'bytes', name: 'data', type: 'bytes' },
    ],
    name: 'upgradeToAndCall',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'version',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'pure',
    type: 'function',
  },
  { inputs: [], name: 'withdraw', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  { stateMutability: 'payable', type: 'receive' },
] as const;
